config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  root 'posts#index'
  get 'index' => 'post_index'
  get 'user_posts' => 'post#user_posts'
  # get 'practice/index'

  # get 'practice/about'
  # root  'practice#index'
  
  # get 'index' => 'practice#index'

  # get 'about' => 'practice#about'

  # post 'index' => 'practice#index'

  # get 'post_index' => 'post#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	  belongs_to :post
	  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	  has_many :comments
	  belongs_to :user
	  # next line for 'kaminari' gem
	  paginates_per 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Next line is for Carrierwave
  mount_uploader :avatar, AvatarUploader
  
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Add next line to use Devise authentication
   before_action :authenticate_user!
  	before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end

end
 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), 
        notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # After doing rails g migration AddValueToComments, we have to manually add
    # the :post_id to the comments params list. The new value represent the id of
    # the post this comment is associated with.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

# Add this to be able to see just a spoecific user's posts
  def user_posts
    @user = User.find(params[:id])
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  # We initiate the variable @commment so we can use it to collect a comment
  # on the Post show page.
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	# text_field_tag in app/views/practice/index.html.erb got us here
  	# e.g., <%= text_field_tag :name, nil, placeholder: "What's your name?" %>
  	# Value entered in text box comes in as params[:name]  
  	@name = params[:name]
  end

  def about
  	# anchor element in app/views/practice/index.html.erb got us here
  	# e.g, <%= link_to "Red", about_path(color: "red") %> 
    # value passed comes in as params[:color]
    # save it as an instance variable
     @color = params[:color]
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- Next 4 divs use Bootstrap Form Classes  -->
  <div class="form-group">
    <!--<%= form.text_area :user_id, value: current_user.id %> -->
    <!-- Thomas' fix -->
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :comment_entry, placeholder: "Tell Me Something...", class: "form-control" %>
  </div>

   <!-- Next def added after post_id field was added to Comments  -->
  <div class="form-group">
    <%= form.hidden_field :post_id, value: @post.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<!-- Added this container div to use bootstrap per TTS slides -->
 	<div class="container">
  		<div class="pull-right">
   			 <% if user_signed_in? %>
     			 <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    		<% end %>
  		</div>
  		<!-- yeild renders the template of the current controller/action-->
    	<%= yield %>
	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- The following Divs were added to use Bootstrap forms -->
  <div class="form-group">
    <%= form.text_field :title, placeholder: "Blog Entry Title", class: "form-control" %>
  </div>

  <!-- Get current_user.id behind the scenes by populating hidden form -->
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.text_area :blog_entry, placeholder: "Tell Us Something...", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Next line assigns color: green in scaffolds.scss -->
<p id="notice"><%= notice %></p>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

  <h1>Current Blog Posts</h1>
  <% @posts.each do |post| %>
    <div class="panel panel-default">
      <!-- <div class="panel-heading"> By ...<%= @post.user.email %></div> -->
      <div class="panel-heading"> 
          By ...<%= link_tp post.user.username, user_posts_path(:id post.user.id) %></div>
        <div class="panel-body"><%= post.blog_entry %></div>
          <div class="panel-footer">
            <button class="btn btn-primary"><%= link_to 'Show', post %></button>
            <button class="btn btn-warning"><%= link_to 'Edit', edit_post_path(post) %></button>
            <button class="btn btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          </div> 
    </div>
  <%end%>
<!-- next line for 'kaminari' -->
<%= paginate @posts %>
<h3>
<%= link_to 'New Blog Post', new_post_path %>
</h3>
</body>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Blog entry:</strong>
  <%= @post.blog_entry %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |

<!-- Allow comments to be added on the post show page -->
<div id="comments">
    <%= render 'comments/form', comment: @comment %>
    <% @post.comments.each do |comment| %>
    	<p>
        <%= link_to comment.user.user_name, user_posts_path(:id comment.user_id)%> said...
        <!-- Following line never worked -->
        <!-- by <%= @post.user.username %> --> 
        <br/>
 	    	<%= comment.comment_entry %>
		</p>
    <% end %>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/user_posts.html.erb
<h1>All Posts by <%= @user.username %></h1>

<% @user.posts.each do |post| %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="well">
        <h3><%= post.title %></h3>
        <p><em>posted on <%= post.created_at.strftime("%B %e, %Y at %l:%M %p") %></em></p>
        <p>
          <%= post.blog_entry.html_safe %>
        </p>
        <p>
          <%= link_to 'Show', post, class: "btn btn-info" %> 
          <% if current_user.id == post.user_id %>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-warning" %> 
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/practice/about.html.erb
<h1>Practice#about</h1>
<p>Find me in app/views/practice/about.html.erb</p>

<!-- Remember, internal stylesheet is not the best,
    but we have no way to get a Ruby instance
    variable into a CSS file, so we don't have
    much of an alternative here

	instance variable @color was set by
    app/controllers/practice_controller.rb about method
    before we got here
     -->
<style>

    #color_me_in {
        background-color: <%= @color %>;
        color: white;
        width: 250px;
        height: 250px;
    }

</style>

<div id="color_me_in">
    <p>
        <%= @color.upcase %> BOX ACTIVATED!
    </p>
</div>

<!-- show a form that takes input and transmits it back to controller's
	 index action
    Since form_tag defaults to POST, we update routes.rb with a post for the index action -->
<%= form_tag index_path do %>
	<!-- text_field_tag creates a text field for user input
		Value entered is stored in :name, gets passed to controller 
		index action where it's retirieved as params[:name]-->
    <p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>
    <p><%= submit_tag "submit" %></p>

<% end %>

app/views/practice/index.html.erb
<!-- <p>app/views/practice/index.html.erb</p> -->
<!--  Ways to get here:  
	1) user typed in URL http://localhost:3000/index
	2) form_tag index_path in about.html.erb -->

<h1>Choose a Color!</h1>

<!-- If user came directly here from URL or didn't enter name in
	text_field_tag.  @name is unknown -->
<% if !@name.blank? %> 
  <h2>Welcome Back, <%= @name %></h2>
<% end %>	

<p>
	<!-- Creates anchor element "Red" that routes to
		controllers/practice_controller.rb about action, i.e., 
		views/practice/about.html.erb -->
	<!-- color: "red" comes to controller action as "params[:color]"-->
	<%= link_to "Red", about_path(color: "red") %>
</p>

<p>
    <%= link_to "Blue", about_path(color: "blue") %>
</p>

<p>
    <%= link_to "Green", about_path(color: "green") %>
</p>

<p>
    <%= link_to "Yellow", about_path(color: "yellow") %>
</p>


<!-- -->

<p>
<%= "Instance Methods" %> <br/>
<%= "PostsController.new.methods-Object.new.methods" %> <br/>
<% @m_arr= (PostsController.new.methods-Object.new.methods).sort%>
<% @m_arr.each do |m| %>
	<%= m %>
	<br/>
<%end%>
</p>